import { useEffect, useState } from 'react'
import { api } from '../services/api.js'
const emptyMovie={title:'',description:'',poster_url:'',genre:'Drama',language:'Hindi',duration:120,release_date:'',rating:7,director:'',cast_members:'',status:'NOW_SHOWING'}
export default function Admin(){
 const [tab,setTab]=useState('dashboard'),[data,setData]=useState([]),[stats,setStats]=useState(null),[error,setError]=useState(''),[movie,setMovie]=useState(emptyMovie),[form,setForm]=useState({}),[editing,setEditing]=useState(null)
 const endpoints={movies:'/admin/movies',cinemas:'/admin/cinemas',screens:'/admin/screens',shows:'/admin/shows',bookings:'/admin/bookings',users:'/admin/users'}
 async function load(name=tab){try{setError('');if(name==='dashboard'){setStats(await api('/admin/stats'));return}setData(await api(endpoints[name]))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[tab])
 async function addMovie(e){e.preventDefault();try{await api(editing?`/admin/movies/${editing}`:'/admin/movies',{method:editing?'PUT':'POST',body:JSON.stringify(movie)});setMovie(emptyMovie);setEditing(null);load('movies')}catch(e){setError(e.message)}}
 async function addCinema(e){e.preventDefault();try{await api(editing?`/admin/cinemas/${editing}`:'/admin/cinemas',{method:editing?'PUT':'POST',body:JSON.stringify(form)});setForm({});setEditing(null);load('cinemas')}catch(e){setError(e.message)}}
 async function addScreen(e){e.preventDefault();try{await api('/admin/screens',{method:'POST',body:JSON.stringify(form)});setForm({});load('screens')}catch(e){setError(e.message)}}
 async function addShow(e){e.preventDefault();try{await api('/admin/shows',{method:'POST',body:JSON.stringify(form)});setForm({});load('shows')}catch(e){setError(e.message)}}
 async function removeMovie(id){if(!confirm('Delete this movie?'))return;try{await api(`/admin/movies/${id}`,{method:'DELETE'});load('movies')}catch(e){setError(e.message)}}
 async function remove(resource,id){if(!confirm(`Delete this ${resource}?`))return;try{await api(`/admin/${resource}/${id}`,{method:'DELETE'});load(tab)}catch(e){setError(e.message)}}
 const field=(label,key,type='text')=><label>{label}<input type={type} required={['title','description','genre','language','duration'].includes(key)} value={movie[key]||''} onChange={e=>setMovie({...movie,[key]:e.target.value})}/></label>
 return <><p className="eyebrow">ADMIN AREA</p><h1 className="page-title">CineVerse dashboard</h1><nav className="admin-tabs">{['dashboard','movies','cinemas','screens','shows','bookings','users'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>{error&&<p className="notice">{error}</p>}
 {tab==='dashboard'&&stats&&<div className="stats">{Object.entries(stats).map(([k,v])=><div className="card" key={k}><b>{v}</b><span>{k}</span></div>)}</div>}
 {tab==='movies'&&<><form className="admin-form card" onSubmit={addMovie}>{field('Title','title')}{field('Description','description')}{field('Poster URL','poster_url')}{field('Genre','genre')}{field('Language','language')}{field('Duration (minutes)','duration','number')}{field('Release date','release_date','date')}{field('Rating','rating','number')}{field('Director','director')}{field('Cast','cast_members')}<button className="btn">{editing?'Save movie':'Add movie'}</button></form><Table rows={data} remove={removeMovie} edit={row=>{setMovie(row);setEditing(row.id)}}/></>}
 {tab==='cinemas'&&<><SimpleForm fields={['name','city','address']} form={form} setForm={setForm} submit={addCinema} button={editing?'Save cinema':'Add cinema'}/><Table rows={data} remove={id=>remove('cinemas',id)} edit={row=>{setForm(row);setEditing(row.id)}}/></>}
 {tab==='screens'&&<><SimpleForm fields={['cinema_id','name']} form={form} setForm={setForm} submit={addScreen} button="Add screen"/><Table rows={data} remove={id=>remove('screens',id)}/></>}
 {tab==='shows'&&<><SimpleForm fields={['movie_id','cinema_id','screen_id','show_date','start_time','end_time','regular_price','premium_price','vip_price']} form={form} setForm={setForm} submit={addShow} button="Create show"/><Table rows={data} remove={id=>remove('shows',id)}/></>}
 {['bookings','users'].includes(tab)&&<Table rows={data}/>}</>
}
function SimpleForm({fields,form,setForm,submit,button}){return <form className="admin-form card" onSubmit={submit}>{fields.map(key=><label key={key}>{key.replace('_',' ')}<input required value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="btn">{button}</button></form>}
function Table({rows,remove,edit}){if(!rows.length)return <p className="tagline">No records yet.</p>;const keys=Object.keys(rows[0]).filter(k=>!['id','poster_url','description','password_hash'].includes(k));return <div className="table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{k.replace('_',' ')}</th>)}{(remove||edit)&&<th>Action</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>{keys.map(k=><td key={k}>{Array.isArray(row[k])?row[k].join(', '):String(row[k]??'').slice(0,50)}</td>)}{(remove||edit)&&<td>{edit&&<button className="danger" onClick={()=>edit(row)}>Edit</button>}{remove&&<button className="danger" onClick={()=>remove(row.id)}>Delete</button>}</td>}</tr>)}</tbody></table></div>}
