import { Router } from 'express'
import pool from '../db/pool.js'
import { requireAdmin, requireAuth } from '../middleware/authMiddleware.js'
const router = Router(); router.use(requireAuth, requireAdmin)
const query = (sql, params, res, next, status = 200) => pool.query(sql, params).then(({ rows }) => res.status(status).json(rows.length === 1 ? rows[0] : rows)).catch(next)

router.get('/stats', async (_req, res, next) => { try { const { rows: [s] } = await pool.query("SELECT (SELECT count(*) FROM movies) movies, (SELECT count(*) FROM cinemas) cinemas, (SELECT count(*) FROM shows) shows, (SELECT count(*) FROM bookings WHERE status='CONFIRMED') bookings, COALESCE((SELECT sum(total_amount) FROM bookings WHERE status='CONFIRMED'),0) revenue"); res.json(s) } catch (e) { next(e) } })
router.get('/users', (_q, res, next) => query('SELECT id,name,email,role,created_at FROM users ORDER BY created_at DESC', [], res, next))
router.get('/bookings', (_q, res, next) => query('SELECT b.*,u.name user_name,m.title movie_title FROM bookings b JOIN users u ON u.id=b.user_id JOIN shows sh ON sh.id=b.show_id JOIN movies m ON m.id=sh.movie_id ORDER BY b.created_at DESC', [], res, next))
router.get('/movies', (_q, res, next) => query('SELECT * FROM movies ORDER BY release_date DESC', [], res, next))
router.post('/movies', (req,res,next) => { const m=req.body; query('INSERT INTO movies (title,description,poster_url,genre,language,duration,release_date,rating,director,cast_members,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[m.title,m.description,m.poster_url,m.genre,m.language,m.duration,m.release_date,m.rating,m.director,m.cast_members,m.status||'NOW_SHOWING'],res,next,201) })
router.put('/movies/:id', (req,res,next) => { const m=req.body; query('UPDATE movies SET title=$1,description=$2,poster_url=$3,genre=$4,language=$5,duration=$6,release_date=$7,rating=$8,director=$9,cast_members=$10,status=$11 WHERE id=$12 RETURNING *',[m.title,m.description,m.poster_url,m.genre,m.language,m.duration,m.release_date,m.rating,m.director,m.cast_members,m.status,req.params.id],res,next) })
router.delete('/movies/:id', async (req,res,next) => { try { const r=await pool.query('DELETE FROM movies WHERE id=$1',[req.params.id]); if(!r.rowCount) return res.status(404).json({message:'Movie not found'}); res.status(204).end() } catch(e){next(e)} })
router.get('/cinemas', (_q,res,next) => query('SELECT c.*, count(sc.id)::int AS screen_count FROM cinemas c LEFT JOIN screens sc ON sc.cinema_id=c.id GROUP BY c.id ORDER BY c.name',[],res,next))
router.post('/cinemas', (req,res,next) => query('INSERT INTO cinemas (name,city,address) VALUES ($1,$2,$3) RETURNING *',[req.body.name,req.body.city,req.body.address],res,next,201))
router.put('/cinemas/:id', (req,res,next) => query('UPDATE cinemas SET name=$1,city=$2,address=$3 WHERE id=$4 RETURNING *',[req.body.name,req.body.city,req.body.address,req.params.id],res,next))
router.delete('/cinemas/:id', async (req,res,next) => { try { const r=await pool.query('DELETE FROM cinemas WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Cinema not found'});res.status(204).end() }catch(e){next(e)} })
router.post('/screens', (req,res,next) => query('INSERT INTO screens (cinema_id,name) VALUES ($1,$2) RETURNING *',[req.body.cinema_id,req.body.name],res,next,201))
router.get('/screens', (_q,res,next) => query('SELECT sc.*,c.name cinema_name FROM screens sc JOIN cinemas c ON c.id=sc.cinema_id ORDER BY c.name,sc.name',[],res,next))
router.delete('/screens/:id', async (req,res,next) => { try { const r=await pool.query('DELETE FROM screens WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Screen not found'});res.status(204).end() }catch(e){next(e)} })
router.post('/seats', async (req,res,next) => { try { const { screen_id, row_label, count=8, seat_type='REGULAR' }=req.body; const client=await pool.connect(); try { await client.query('BEGIN'); for(let n=1;n<=Number(count);n++) await client.query('INSERT INTO seats (screen_id,row_label,seat_number,seat_type) VALUES ($1,$2,$3,$4)',[screen_id,row_label,n,seat_type]); await client.query('COMMIT'); res.status(201).json({message:`${count} seats added`}) } catch(e) { await client.query('ROLLBACK'); throw e } finally { client.release() } } catch(e){next(e)} })
router.get('/shows', (_q,res,next) => query('SELECT sh.*,m.title movie_title,c.name cinema_name,sc.name screen_name FROM shows sh JOIN movies m ON m.id=sh.movie_id JOIN cinemas c ON c.id=sh.cinema_id JOIN screens sc ON sc.id=sh.screen_id ORDER BY sh.show_date,sh.start_time',[],res,next))
router.post('/shows', (req,res,next) => { const s=req.body; query('INSERT INTO shows (movie_id,cinema_id,screen_id,show_date,start_time,end_time,regular_price,premium_price,vip_price) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[s.movie_id,s.cinema_id,s.screen_id,s.show_date,s.start_time,s.end_time,s.regular_price,s.premium_price,s.vip_price],res,next,201) })
router.put('/shows/:id', (req,res,next) => { const s=req.body; query('UPDATE shows SET movie_id=$1,cinema_id=$2,screen_id=$3,show_date=$4,start_time=$5,end_time=$6,regular_price=$7,premium_price=$8,vip_price=$9 WHERE id=$10 RETURNING *',[s.movie_id,s.cinema_id,s.screen_id,s.show_date,s.start_time,s.end_time,s.regular_price,s.premium_price,s.vip_price,req.params.id],res,next) })
router.delete('/shows/:id', async (req,res,next) => { try { const r=await pool.query('DELETE FROM shows WHERE id=$1',[req.params.id]); if(!r.rowCount)return res.status(404).json({message:'Show not found'});res.status(204).end()}catch(e){next(e)} })
export default router
